// <auto-generated />
using System;
using ITIApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312140131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITIApp.DAL.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Duration = 40,
                            InstructorId = 1,
                            IsDeleted = false,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Duration = 35,
                            InstructorId = 2,
                            IsDeleted = false,
                            Name = "Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Duration = 45,
                            InstructorId = 3,
                            IsDeleted = false,
                            Name = "Calculus I"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Duration = 30,
                            InstructorId = 3,
                            IsDeleted = false,
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Duration = 40,
                            InstructorId = 4,
                            IsDeleted = false,
                            Name = "Mechanics"
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<int>("InsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CrsId");

                    b.HasIndex("InsId");

                    b.ToTable("CourseSessios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrsId = 1,
                            InsId = 1,
                            IsDeleted = false,
                            SessionDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intro to C#"
                        },
                        new
                        {
                            Id = 2,
                            CrsId = 1,
                            InsId = 1,
                            IsDeleted = false,
                            SessionDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "OOP Basics"
                        },
                        new
                        {
                            Id = 3,
                            CrsId = 2,
                            InsId = 2,
                            IsDeleted = false,
                            SessionDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Arrays & Lists"
                        },
                        new
                        {
                            Id = 4,
                            CrsId = 3,
                            InsId = 3,
                            IsDeleted = false,
                            SessionDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Limits"
                        },
                        new
                        {
                            Id = 5,
                            CrsId = 4,
                            InsId = 3,
                            IsDeleted = false,
                            SessionDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vectors"
                        },
                        new
                        {
                            Id = 6,
                            CrsId = 5,
                            InsId = 4,
                            IsDeleted = false,
                            SessionDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Newton's Laws"
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.CourseSessionAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CrsSessionId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrsSessionId");

                    b.HasIndex("StId");

                    b.ToTable("CourseSessionAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CrsSessionId = 1,
                            Grade = 90,
                            Notes = "Excellent",
                            StId = 1
                        },
                        new
                        {
                            Id = 2,
                            CrsSessionId = 1,
                            Grade = 75,
                            Notes = "Good",
                            StId = 2
                        },
                        new
                        {
                            Id = 3,
                            CrsSessionId = 2,
                            Grade = 85,
                            Notes = "Very Good",
                            StId = 1
                        },
                        new
                        {
                            Id = 4,
                            CrsSessionId = 3,
                            Grade = 70,
                            StId = 1
                        },
                        new
                        {
                            Id = 5,
                            CrsSessionId = 3,
                            Grade = 95,
                            Notes = "Top scorer",
                            StId = 3
                        },
                        new
                        {
                            Id = 6,
                            CrsSessionId = 4,
                            Grade = 80,
                            StId = 4
                        },
                        new
                        {
                            Id = 7,
                            CrsSessionId = 5,
                            Grade = 88,
                            Notes = "Good effort",
                            StId = 5
                        },
                        new
                        {
                            Id = 8,
                            CrsSessionId = 6,
                            Grade = 100,
                            Notes = "Absent",
                            StId = 3
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Building A",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Building B",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Building C",
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagedDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("ManagedDepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeptId = 1,
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Phone = "010-1234-5678"
                        },
                        new
                        {
                            Id = 2,
                            DeptId = 1,
                            FirstName = "Sara",
                            LastName = "Mohamed",
                            Phone = "011-2345-6789"
                        },
                        new
                        {
                            Id = 3,
                            DeptId = 2,
                            FirstName = "Omar",
                            LastName = "Hassan",
                            Phone = "012-3456-7890"
                        },
                        new
                        {
                            Id = 4,
                            DeptId = 3,
                            FirstName = "Nadia",
                            LastName = "Kamal",
                            Phone = "010-4567-8901"
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.StCourses", b =>
                {
                    b.Property<int>("StId")
                        .HasColumnType("int");

                    b.Property<int>("CrsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("StId", "CrsId");

                    b.HasIndex("CrsId");

                    b.ToTable("StCourses");

                    b.HasData(
                        new
                        {
                            StId = 1,
                            CrsId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 2,
                            CrsId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 1,
                            CrsId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 3,
                            CrsId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 4,
                            CrsId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 4,
                            CrsId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 5,
                            CrsId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            StId = 3,
                            CrsId = 5,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ali",
                            LastName = "Hassan",
                            Phone = "010-1111-2222"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Mona",
                            LastName = "Ahmed",
                            Phone = "011-2222-3333"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Khaled",
                            LastName = "Ibrahim",
                            Phone = "012-3333-4444"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Yasmine",
                            LastName = "Omar",
                            Phone = "010-4444-5555"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Tarek",
                            LastName = "Samir",
                            Phone = "011-5555-6666"
                        });
                });

            modelBuilder.Entity("ITIApp.DAL.Course", b =>
                {
                    b.HasOne("ITIApp.DAL.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIApp.DAL.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ITIApp.DAL.CourseSession", b =>
                {
                    b.HasOne("ITIApp.DAL.Course", "Course")
                        .WithMany("CourseSessions")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIApp.DAL.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ITIApp.DAL.CourseSessionAttendance", b =>
                {
                    b.HasOne("ITIApp.DAL.CourseSession", "CourseSession")
                        .WithMany("CourseSessionAttendances")
                        .HasForeignKey("CrsSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIApp.DAL.Student", "Student")
                        .WithMany("CourseSessionAttendances")
                        .HasForeignKey("StId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIApp.DAL.Department", b =>
                {
                    b.HasOne("ITIApp.DAL.Instructor", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ITIApp.DAL.Instructor", b =>
                {
                    b.HasOne("ITIApp.DAL.Department", "Department")
                        .WithMany("Instuctors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITIApp.DAL.Department", "ManagedDepartment")
                        .WithMany()
                        .HasForeignKey("ManagedDepartmentId");

                    b.Navigation("Department");

                    b.Navigation("ManagedDepartment");
                });

            modelBuilder.Entity("ITIApp.DAL.StCourses", b =>
                {
                    b.HasOne("ITIApp.DAL.Course", "Course")
                        .WithMany("StCourses")
                        .HasForeignKey("CrsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITIApp.DAL.Student", "Student")
                        .WithMany("StCourses")
                        .HasForeignKey("StId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIApp.DAL.Course", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("StCourses");
                });

            modelBuilder.Entity("ITIApp.DAL.CourseSession", b =>
                {
                    b.Navigation("CourseSessionAttendances");
                });

            modelBuilder.Entity("ITIApp.DAL.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instuctors");
                });

            modelBuilder.Entity("ITIApp.DAL.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("ITIApp.DAL.Student", b =>
                {
                    b.Navigation("CourseSessionAttendances");

                    b.Navigation("StCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
